export const actionType = {
    //auth
    ADD_USER : "ADD_USER",
    SET_LOGIN : "SET_LOGIN",
    GET_USER : "GET_USER",
    LOG_OUT : "LOG_OUT",
    EDIT_PROFILE : "EDIT_PROFILE",
    CHANGE_PROFILE : "CHANGE_PROFILE",
    DELETE_PROFILE : "DELETE_PROFILE",
    ADD_PROFILE  :"ADD_PROFILE",

    //product
    DELETE_PRODUCT : "DELETE_PRODUCT",
    ADD_PRODUCT : "ADD_PRODUCT",
    DECREASE_PRODUCT  : "DECREASE_PRODUCT",
    INCREASE_PRODUCT : "INCREASE_PRODUCT",
    EDIT_PRODUCT : "EDIT_PRODUCT",
    CHANGE_PRODUCT : "CHANGE_PRODUCT",
}

Object.freeze(actionType);